# fly.toml app configuration file generated for songaday on 2023-12-30T23:37:24Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "songaday"
primary_region = "lhr"

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[mounts]
source = "user_info"
destination = "/info"


[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024
